# Generated by Django 3.2.5 on 2021-07-11 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20210710_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, choices=[('p1', '강아지'), ('p2', '고양이'), ('p3', '햄스터'), ('p4', '포유류'), ('p5', '조류'), ('p6', '어류'), ('p7', '파충류'), ('p8', '거미/전갈')], max_length=2, null=True, verbose_name='category')),
                ('introduction', models.CharField(blank=True, max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/')),
                ('follow_users', models.ManyToManyField(blank=True, related_name='follow_pets', through='pets.Follow', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='follow',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
