
# Generated by Django 3.2.5 on 2021-07-11 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='category',
            field=models.CharField(choices=[('p1', '강아지'), ('p2', '고양이'), ('p3', '햄스터'), ('p4', '포유류'), ('p5', '조류'), ('p6', '어류'), ('p7', '파충류'), ('p8', '거미/전갈')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='follow_users',
            field=models.ManyToManyField(blank=True, related_name='following_pets', through='pets.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
