# Generated by Django 3.2.5 on 2021-07-11 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='follow_users',
            field=models.ManyToManyField(blank=True, related_name='following_pets', through='pets.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
