# Generated by Django 3.2.3 on 2021-07-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20210711_1503'),
        ('pets', '0003_alter_pet_category'),
    ]

    operations = [
    ]
