# Generated by Django 3.2.3 on 2021-07-11 14:03

from django.conf import settings
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0005_alter_pet_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='follow_users',
            field=models.ManyToManyField(blank=True, related_name='follow_pets', through='pets.Follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
