# Generated by Django 3.2.5 on 2021-07-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210710_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='follow_users',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
